#!/bin/bash
#
# Script to rename libvmod-pupa into libvmod-foo.
# (where "foo" is your new vmod name, of course.)
#
# Leaves the changes uncommitted in the working tree, so you get to fix any
# unintended changes.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, September 2014.
#
set -o errexit

NAME=$1
if [ -z "$NAME" ]; then
	echo "Usage: $0 <new-vmod-name-without-libvmod-prefix>"
	echo "Rename libvmod-pupa source tree."
	echo
	exit -1
fi

if ! git diff-index --quiet HEAD --; then
	echo "ERROR: Need a clean working tree. Run \"git stash\" first."
	exit -2
fi

git mv src/pupa.rs src/${NAME}.rs
git mv src/vmod_pupa.vcc src/vmod_${NAME}.vcc
git mv vmod-pupa.spec vmod-${NAME}.spec

git grep -z -l pupa | xargs -0 sed -i -s -e "s/pupa/${NAME}/g"

git rm -f rename-vmod-script

echo "All done."
echo -e "For your copy&paste needs:\n  git commit -a -m \"Automatic rename of libvmod-pupa to libvmod-${NAME}.\""


